### PR TITLE
Ignore entries for other buffers

### PR DESCRIPTION
**Pull request by AndrewRadev**
Really cool idea for a plugin -- I can definitely see myself keeping it on by default, although I use the global quickfix list rather than the location list. But that's a different topic.

I'm seeing a problem when the location list has entries for multiple buffers. For instance, in this project directory, you could run this:

``` vim
:lvimgrep /loclist/ **
```

As a result, the location list is going to have entries both from `README.md` and from `plugin/loclist-follow.vim`. However, because the plugin only checks the *first* element of the list for the right buffer, scrolling too far down in the README ends up with a line that matches a later entry, which is in a different buffer. So, Vim unexpectedly ends up jumping to the plugin file as you scroll down.

Additionally, in that buffer, the plugin no longer tracks the cursor position, because the initial check is for the very first item, a line in the README, and you're currently in the plugin file instead.

The PR hacks around this by inserting a buffer check in the comparison while loops and in the column loop. If any of these checks that update the buffer end up finding a "better" match, but that match is in a different buffer, the function returns and the match is not updated.

I'm not sure if this fixes all scenarios, and I don't know if it's a reasonable solution. It would be simpler to stop looping when hitting an entry for a different buffer, but there's no guarantee the list will be grouped by buffer -- it's possible to add entries via `laddb`, or even directly with `setloclist`. 

If I had more time and energy, I'd consider restructuring the code, so it fetches the list and filters out only the relevant items first, sorts them, maybe attaches the source `idx` to the hash entries, so that later looping can be guaranteed to only go through buffer-local entries. Then, the jump might be an `exe "ll ".best_entry.source_idx` or something.

What I'm saying is, consider the PR more of a suggestion -- if you have a different solution to the problem, or there's issues with it I didn't predict, feel free to close it.

### CODE REVIEW

**Comment by elbeardmorez** [comment]
Very much appreciate your efforts and interest, thank you, and I can only apologise for missing your PR until just after I'd pushed the last few days of efforts (i.e. I pushed, then checked here, and only then noticed your activity). For some reason 'watch' wasn't set as the default for me (which for my own repository seems a little ridiculous github!), fixed now so I'll get future notices but consequently now, your PR doesn't apply cleanly.

You've essentially explained the scenario (very well) that led the short-circuit you remove to be added in the first place ..the use case that triggered it was simply opening an alternative file in a buffer window that had an associated (populated) location list. I believe Syntastic (where I started) didn't automatically clear/close in the event a different file was read, and that led to the exact same outcome you describe - a rather amusing / confusing bug as I remember! This might actually be different now I've rewired the hooks.. not sure.

The issue I see with the proposal is that without a short-circuit of some sort, we're potentially looping the entire location list on every cursor movement, something I explicitly wanted to avoid, and hence the approach of holding the last idx/pos and using that as a start point for searching for the next.

Can't think of better way to do it than your latter suggestion.. and maybe it'll be fine given we can discern qf from loclist windows and thus apply different logic. I'll knock something up asap and of course credit you with some aspect of the work.

**Comment by AndrewRadev** [comment]
No worries about missing the PR, and yes, I see the problem with looping the whole list. Keeping a sorted list of entries might be the way to go. I'd consider also a dictionary with `{ <buffer_number>: [<sorted entries] }`. That way, you could even do a binary search (though I don't think it'd be necessary).

The only question would be when to generate it. There's a `QuickFixCmdPost` autocommand, but that one is not invoked with a manual `setqflist()` or `setloclist()` invocation, and I'd imagine lots of plugins use that. I'd consider generating it on a `BufEnter` on the quickfix window, which you already have from what I could see. Maybe one on `QuickFixCmdPost` as well, just in case one of the "add" commands doesn't move the cursor on top of the location list window.

Anyway, I leave it to you to figure out something sensible. Not in a rush myself, so take your time.

**Comment by elbeardmorez** [comment]
We'll see how the simple method works first I think. Still seems nice and zippy to me. I'll hold off releasing this for a day or so, so if you have any issues with your usage please do shout. Given your other issue was implemented verbatim I've elected to push and credit you there - hope that is fine. Thanks.

**Comment by elbeardmorez** [comment]
*Note, must also say thanks for the `lvimgrep` example.. very very useful indeed!

**Comment by AndrewRadev** [comment]
Works well for me, thanks! I'll keep using it and report if I run into any issues, with performance as well, but so far, it seems to add no overhead at all.

**Pull request closed without merging**
